// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANw_O96UfKElIxO950cpFkneSbHao1GCc',
    appId: '1:323986191759:web:7177d131d25926926d87fa',
    messagingSenderId: '323986191759',
    projectId: 'lets-chat-507df',
    authDomain: 'lets-chat-507df.firebaseapp.com',
    storageBucket: 'lets-chat-507df.appspot.com',
    measurementId: 'G-324NXWT3XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCfSHggbSduU0QwRByPQ3-gx8DqaMWZE',
    appId: '1:323986191759:android:43fb36626fc697136d87fa',
    messagingSenderId: '323986191759',
    projectId: 'lets-chat-507df',
    storageBucket: 'lets-chat-507df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbx8gy2BJPNNMVefx_lXPoYFZ-4XFGmIA',
    appId: '1:323986191759:ios:ea4f06a75ab699406d87fa',
    messagingSenderId: '323986191759',
    projectId: 'lets-chat-507df',
    storageBucket: 'lets-chat-507df.appspot.com',
    androidClientId: '323986191759-sg195q49ruor5tt2hb3t7kufen8kse7o.apps.googleusercontent.com',
    iosClientId: '323986191759-2ucfpr4iq12r3uboq8al3p70glov296i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbx8gy2BJPNNMVefx_lXPoYFZ-4XFGmIA',
    appId: '1:323986191759:ios:ea4f06a75ab699406d87fa',
    messagingSenderId: '323986191759',
    projectId: 'lets-chat-507df',
    storageBucket: 'lets-chat-507df.appspot.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANw_O96UfKElIxO950cpFkneSbHao1GCc',
    appId: '1:323986191759:web:ba4424faf7b8bfe06d87fa',
    messagingSenderId: '323986191759',
    projectId: 'lets-chat-507df',
    authDomain: 'lets-chat-507df.firebaseapp.com',
    storageBucket: 'lets-chat-507df.appspot.com',
    measurementId: 'G-BB8X29TER5',
  );

}